import Navbar from '@/components/Global/Navbar'
import './globals.css'
import { Inter, Nothing_You_Could_Do } from 'next/font/google'
import Footer from '@/components/Global/Footer'

const inter = Inter({ subsets: ['latin'] })
const nycd = Nothing_You_Could_Do({ subsets: ['latin'], weight: '400' })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en" data-theme='light'>
			<body className={inter.className}>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	)
}
